runtime: custom
env: flex
service: backend

instance_class: F1

# Resource settings
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 20

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.65

# Health check configuration
liveness_check:
  path: "/_ah/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 2
  initial_delay_sec: 120

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 2
  app_start_timeout_sec: 600

env_variables:
  NODE_ENV: "production"
  HUGGINGFACE_API_KEY: "YOUR_HUGGINGFACE_API_KEY"
  UPLOAD_DIR: "/tmp/uploads"
  PYTHONPATH: "/app/venv/lib/python3.9/site-packages"

handlers:
  - url: /.*
    script: auto
    secure: always 