services:
  - type: web
    name: verifai-backend
    env: node
    buildCommand: chmod +x start.sh && npm install && pip install -r ../requirements.txt
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: HUGGINGFACE_API_KEY
        sync: false 